#
# K2HASH
#
# Utility tools for building configure/packages by AntPickax
#
# Copyright 2018 Yahoo Japan corporation.
#
# AntPickax provides utility tools for supporting autotools
# builds.
#
# These tools retrieve the necessary information from the
# repository and appropriately set the setting values of
# configure, Makefile, spec,etc file and so on.
# These tools were recreated to reduce the number of fixes and
# reduce the workload of developers when there is a change in
# the project configuration.
# 
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#
# AUTHOR:   Takeshi Nakatani
# CREATE:   Wed 7 Dec 2016
# REVISION:
#

language: cpp

sudo: required

dist: trusty

env:
  global:
    - PCUSER=antpickax
    - PCREPO=current
    - PCDLREPO=stable
  matrix:
    - OS=fedora 
      TAG=29 
      DISTTAG=fedora/29 
      CONFIGUREOPT="--with-nss" 
      K2HATTR_ENC_TYPE=AES256_PBKDF2 
      INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems procps libfullock-devel nss-devel"

cache: apt

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker image pull ${OS}:${TAG}

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export PCTOKEN=dummy_token_for_pr; else export PCTOKEN=${PACKAGECLOUD_TOKEN}; fi'
  - docker container run 
    --rm=true 
    -e TRAVIS_TAG=${TRAVIS_TAG} 
    -e FORCE_BUILD_PKG=${FORCE_BUILD_PKG} 
    -e USE_PC_REPO=${USE_PC_REPO} 
    -e BUILD_NUMBER=${BUILD_NUMBER} 
    -e DEBFULLNAME=${DEBFULLNAME} 
    -e DEBEMAIL=${DEBEMAIL} 
    -e CONFIGUREOPT=${CONFIGUREOPT} 
    -e K2HATTR_ENC_TYPE=${K2HATTR_ENC_TYPE} 
    -v `pwd`:/k2hash:rw ${OS}:${TAG} 
    /bin/sh -c "/k2hash/buildutils/travis_builder.sh -${OS} -pctoken ${PCTOKEN} -pcuser ${PCUSER} -pcrepo ${PCREPO} -pcdlrepo ${PCDLREPO} -pcdist ${DISTTAG} ${INSTPKG}"

#
# VIM modelines
#
# vim:set ts=4 fenc=utf-8:
#
